### ISSUE TITLE
recipe compile error in c:\C:\chef\local-mode-cache\cache\cookbooks\arcgis-enterprise\recipes\server.rb

### ISSUE THREAD

**Issue by tysontaylor** [Esri/arcgis-cookbook#112]
Ran a script fine, but the second time i  run it i am getting this error any ideas.

ArgumentError

Generated at 2017-09-07 14:17:51 -0600
ArgumentError: You must supply a name when declaring a file resource
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_builder.rb:46:in `build'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/dsl/declare_resource.rb:291:in `build_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/dsl/declare_resource.rb:248:in `declare_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/dsl/resources.rb:40:in `file'
c:/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/recipes/server.rb:85:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/cookbook_version.rb:233:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/run_context.rb:338:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:141:in `block in compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/run_context.rb:187:in `load'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:511:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:281:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:276:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:252:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:235:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/solo.rb:226:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/bin/chef-solo:25:in `<top (required)>'
C:/opscode/chef/bin/chef-solo:68:in `load'
C:/opscode/chef/bin/chef-solo:68:in `<main>'

**Comment by tysontaylor** [comment]
This is the script i am trying to run .  I ran fine earlier yesterday.   
{
  "arcgis":{
    "run_as_password":"xxx",
    "run_as_user":"xxx",
    "version":"10.5",
    "server":{
      "admin_username":"xxx",
      "admin_password":"xxx",
      "directories_root":"C:\\arcgisserver",
      "services" : [
        {
          "folder" : "Base",
          "name" : "Conda_3",
          "type" : "MapServer",
          "definition_file" : "\\\\xxx\\GIS105Data\\AGS_SD\\Dev\\AB_xx.sd",
          "properties" : {
            "maxInstancesPerNode" : 4
          }
        }, {
          "folder" : "Base",
          "name" : "Conda_2",
          "type" : "MapServer",
          "definition_file" : "\\\\xxx\\GIS105Data\\AGS_SD\\Dev\\AB_xx.sd"
        }
      ]
    }
  },
  "run_list":[
    "recipe[arcgis-enterprise::server]",
    "recipe[arcgis-enterprise::services]"
  ]
}

**Comment by tysontaylor** [comment]
i figured it out syntax error
