### ISSUE TITLE
arcgis-enterprise Fails with Chef Version 13.4.24

### ISSUE THREAD

**Issue by ZianAtFirstWatch** [Esri/arcgis-cookbook#115]
Given the following roles file:
```
{
  "arcgis":{
    "run_as_user":"username",
    "run_as_password":"bleep",
    "version":"10.5.1",
    "data_store":{
      "setup":"bleep.exe"
    },
    "server":{
      "admin_username":"fwadmin",
      "admin_password":"937$ch1O1",
      "setup":"another_bleep.exe",
      "authorization_file":"C:\\Users\\bleep\\Desktop\\ArcGISGISServerStandard_ArcGISServer.prvc"
    }
  },
  "run_list":[
    "recipe[arcgis-enterprise::system]",
    "recipe[arcgis-enterprise::server]",
    "recipe[arcgis-enterprise::datastore]"
  ]
}
```
Chef says:
```
[2017-10-02T11:59:56-07:00] ERROR: Running exception handlers
[2017-10-02T11:59:56-07:00] ERROR: Running exception handlers
Running handlers complete
[2017-10-02T11:59:56-07:00] ERROR: Exception handlers complete
[2017-10-02T11:59:56-07:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 20 seconds
[2017-10-02T11:59:56-07:00] FATAL: Stacktrace dumped to c:/chef/local-mode-cache/cache/chef-stacktrace.out
[2017-10-02T11:59:56-07:00] FATAL: Stacktrace dumped to c:/chef/local-mode-cache/cache/chef-stacktrace.out
[2017-10-02T11:59:56-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-10-02T11:59:56-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-10-02T11:59:56-07:00] FATAL: Chef::Exceptions::CookbookChefVersionMismatch: Cookbook 'arcgis-enterprise' version '
3.1.0' depends on chef version ["< 13.0", ">= 12.6"], but the running chef version is 13.4.24
[2017-10-02T11:59:56-07:00] FATAL: Chef::Exceptions::CookbookChefVersionMismatch: Cookbook 'arcgis-enterprise' version '
3.1.0' depends on chef version ["< 13.0", ">= 12.6"], but the running chef version is 13.4.24
PS C:\Windows\system32>
```

More specifically, chef-stacktrace.out says:

```
Generated at 2017-10-02 11:59:56 -0700
Chef::Exceptions::CookbookChefVersionMismatch: Cookbook 'arcgis-enterprise' version '3.1.0' depends on chef version ["< 13.0", ">= 12.6"], but the running chef version is 13.4.24
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/cookbook/metadata.rb:612:in `validate_chef_version!'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/cookbook/cookbook_collection.rb:54:in `block in validate!'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/cookbook/cookbook_collection.rb:53:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/cookbook/cookbook_collection.rb:53:in `validate!'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/policy_builder/expand_node_object.rb:85:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/client.rb:513:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/client.rb:281:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/application.rb:273:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/application.rb:249:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/application.rb:232:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/application/client.rb:457:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/application/client.rb:457:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/application/client.rb:441:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/application/solo.rb:225:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/bin/chef-solo:25:in `<top (required)>'
C:/opscode/chef/bin/chef-solo:58:in `load'
C:/opscode/chef/bin/chef-solo:58:in `<main>'
```

**Comment by pbobov** [comment]
Chef-client 13 is not supported by ArcGIS Chef cookbooks 3.1.0.

**Comment by mschoelen** [comment]
@EsriGithub  Does someone have documentation on how to knife bootstrap a client with the older version that is comparable?
