### ISSUE TITLE
RuntimeError: Invalid Token when configuring HTTPS for Portal

### ISSUE THREAD

**Issue by mschoelen** [Esri/arcgis-cookbook#136]
We are getting the following error message when installing portal with Chef:

> [2018-02-08T11:38:31-05:00] FATAL: RuntimeError: arcgis_enterprise_portal[Configure HTTPS] (arcgis-enterprise::portal line 133) had an error: RuntimeError: Invalid Token.

Digging through the code, it looks like it reaches out to `"portal URL" + /sharing/generateToken` to generate the token. I would imagine that if it couldn't reach that URL, we would get an error message? 

Is it possible that we incorrectly defined our [portal] [url]?

```
>   * arcgis_enterprise_portal[Configure HTTPS] action configure_https[2018-02-08T11:38:29-05:00] INFO: Processing arcgis_
> enterprise_portal[Configure HTTPS] action configure_https (arcgis-enterprise::portal line 133)
> 
> 
>     ================================================================================
>     Error executing action `configure_https` on resource 'arcgis_enterprise_portal[Configure HTTPS]'
>     ================================================================================
> 
>     RuntimeError
>     ------------
>     Invalid Token.
> 
>     Cookbook Trace:
>     ---------------
>     c:/chef/cache/cookbooks/arcgis-enterprise/libraries/portal_admin_client.rb:199:in `import_server_ssl_certificate'
>     c:/chef/cache/cookbooks/arcgis-enterprise/providers/portal.rb:406:in `block in class_from_file'
> 
>     Resource Declaration:
>     ---------------------
>     # In c:/chef/cache/cookbooks/arcgis-enterprise/recipes/portal.rb
> 
>     133: arcgis_enterprise_portal 'Configure HTTPS' do
>     134:   portal_url node['arcgis']['portal']['url']
>     135:   username node['arcgis']['portal']['admin_username']
>     136:   password node['arcgis']['portal']['admin_password']
>     137:   keystore_file node['arcgis']['portal']['keystore_file']
>     138:   keystore_password node['arcgis']['portal']['keystore_password']
>     139:   cert_alias node['arcgis']['portal']['cert_alias']
>     140:   not_if { node['arcgis']['portal']['keystore_file'].empty? }
>     141:   action :configure_https
>     142: end
> 
>     Compiled Resource:
>     ------------------
>     # Declared in c:/chef/cache/cookbooks/arcgis-enterprise/recipes/portal.rb:133:in `from_file'
> 
>     arcgis_enterprise_portal("Configure HTTPS") do
>       action [:configure_https]
>       retries 0
>       retry_delay 2
>       default_guard_interpreter :default
>       declared_type :arcgis_enterprise_portal
>       cookbook_name "arcgis-enterprise"
>       recipe_name "portal"
>       portal_url "https://sstaff.gis.website.com:7443/arcgis"
>       username "admin"
>       password "changeit"
>       content_store_type "fileStore"
>       content_store_provider "FileSystem"
>       log_level "WARNING"
>       keystore_file "\\\\serverp01\\Install\\cert\\newcert\\star.gis.website.com.pfx"
>       keystore_password "PASSWORD"
>       cert_alias "sstaff.gis.website.com"
>       not_if { #code block }
>     end
> 
>     System Info:
>     ------------
>     chef_version=12.21.3
>     platform=windows
>     platform_version=6.1.7601
>     ruby=ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]
>     program_name=C:/opscode/chef/bin/chef-client
>     executable=C:/opscode/chef/bin/chef-client
> 
> [2018-02-08T11:38:31-05:00] INFO: Running queued delayed notifications before re-raising exception
> 
> Running handlers:
> [2018-02-08T11:38:31-05:00] ERROR: Running exception handlers
> Running handlers complete
> [2018-02-08T11:38:31-05:00] ERROR: Exception handlers complete
> Chef Client failed. 3 resources updated in 54 seconds
> [2018-02-08T11:38:31-05:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
> [2018-02-08T11:38:31-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
> [2018-02-08T11:38:31-05:00] FATAL: RuntimeError: arcgis_enterprise_portal[Configure HTTPS] (arcgis-enterprise::portal li
> ne 133) had an error: RuntimeError: Invalid Token.
```

**Comment by pbobov** [comment]
configure_https action is seldom used because in most cases the SSL certificate is installed on the front-end IIS. There might be some issues in the cookbook (like invalid referrer).

Is it actually required to install the SSL certificate on portal in this case?

**Comment by mschoelen** [comment]
If installing it only on IIS is suffecient for HTTPS, then nope. So I'll remove the certificate attributes from the portal side of things?

**Comment by pbobov** [comment]
Yes. If you don't specify arcgis/portal/keystore_file and arcgis/portal/keystore_password attributes, chef will not try to install the SSL certificate on portal.
