### ISSUE TITLE
Installtion log errors

### ISSUE THREAD

**Issue by pkdavidson** [Esri/arcgis-cookbook#17]
Ran the following as test to see how the setup is working.
This is a straight "chef-solo -j C:\chef\node-IIS-1.json"
Here's the json:
{
   "iis" : {
     "keystore_file":"C:\\ArcGIS10.3.1\\internalSHA.pfx",
     "keystore_password":"somepassword"
   },
   "arcgis" : {
 	 "run_as_password" : "pword34$",
	 "run_as_user" : "arcgis"
   },
   "run_list":[
      "recipe[arcgis::system]",
      "recipe[arcgis::iis]"
   ]
}

(actually, this had the datastore, server, etc... sections in the json, but since they weren't used to run, I pulled them out for clarity.

The log file is giving an error about a private key.
However, it looks like the process ran ok.
IIS has the imported CA cert in place.

Because the Client-Service is running, here's the C:\Chef\client.log file:
# Logfile created on 2015-08-20 22:31:11 -0600 by logger.rb/41954
[2015-08-20T22:31:11-06:00] INFO: Chef Client Service initialized
[2015-08-20T22:31:16-06:00] INFO: Next chef-client run will happen in 0.5988767237930117 seconds
[2015-08-20T22:31:19-06:00] INFO: Reconfiguring with startup parameters
[2015-08-20T22:31:21-06:00] WARN: *****************************************
[2015-08-20T22:31:22-06:00] WARN: Did not find config file: C:/chef/client.rb, using command line options.
[2015-08-20T22:31:23-06:00] WARN: *****************************************
[2015-08-20T22:31:25-06:00] INFO: Chef-Client service is starting a chef-client run...
[2015-08-20T22:31:25-06:00] INFO: Starting chef-client in a new process
[2015-08-20T22:31:35-06:00] INFO: *** Chef 12.4.1 ***
[2015-08-20T22:31:35-06:00] INFO: Chef-client pid: 1088
[2015-08-20T22:31:56-06:00] INFO: Client key C:\chef\client.pem is not present - registering
[2015-08-20T22:31:56-06:00] WARN: Failed to read the private key C:\chef\validation.pem: #<Errno::ENOENT: No such file or directory - C:\chef\validation.pem>
[2015-08-20T22:31:56-06:00] ERROR: Running exception handlers
[2015-08-20T22:31:56-06:00] ERROR: Exception handlers complete
[2015-08-20T22:31:56-06:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2015-08-20T22:31:56-06:00] FATAL: Chef::Exceptions::PrivateKeyMissing: I cannot read C:\chef\validation.pem, which you told me to use to sign requests!
[2015-08-20T22:32:07-06:00] INFO: Child process exited (pid: 2068)
[2015-08-20T22:32:08-06:00] INFO: Next chef-client run will happen in 1800.9550718265598 seconds

and the C:\Chef\cache\chef-stacktrace.out:
Generated at 2015-08-20 22:31:56 -0600
Chef::Exceptions::PrivateKeyMissing: I cannot read C:\chef\validation.pem, which you told me to use to sign requests!
C:/opscode/chef/embedded/apps/chef/lib/chef/http/authenticator.rb:86:in `rescue in load_signing_key'
C:/opscode/chef/embedded/apps/chef/lib/chef/http/authenticator.rb:76:in `load_signing_key'
C:/opscode/chef/embedded/apps/chef/lib/chef/http/authenticator.rb:40:in `initialize'
C:/opscode/chef/embedded/apps/chef/lib/chef/rest.rb:71:in `new'
C:/opscode/chef/embedded/apps/chef/lib/chef/rest.rb:71:in `initialize'
C:/opscode/chef/embedded/apps/chef/lib/chef/api_client/registration.rb:125:in `new'
C:/opscode/chef/embedded/apps/chef/lib/chef/api_client/registration.rb:125:in `http_api'
C:/opscode/chef/embedded/apps/chef/lib/chef/api_client/registration.rb:93:in `create'
C:/opscode/chef/embedded/apps/chef/lib/chef/api_client/registration.rb:84:in `create_or_update'
C:/opscode/chef/embedded/apps/chef/lib/chef/api_client/registration.rb:57:in `run'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:608:in `register'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:253:in `run'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:229:in `block in run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:375:in `run_application'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:67:in `load'
C:/opscode/chef/bin/chef-client:67:in `<main>'

Do I need to worry about these?
And where would I get the validation.pem to drop into C:\Chef to quiet down this error?

Running the rest of the install of ArcGIS Server, web adaptor, portal, etc.. now.
Looks like it might go fine now that I have created the local admin account, logged in as that account and put the account info and passwords into the json correctly.

BTW - I do get a lot of warning errors about:
[2015-08-20T22:32:12-06:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead.

I forgot to redirect & Tee the chef-solo output to a log file but it looks like the pkey error is not an issue.  It's now past data store and into Portal.

I'm assuming that to turn this setup into HTTPS Only and federate it into WIA, I do that by hand via Manager, etc...?

Thanks...  This tool is going to save a lot of folks a lot of time and headaches.

**Comment by pbobov** [comment]
Hi Paul,

It looks like this log file was created by the chef client windows service that runs periodically on your machine and not by chef-solo. Please try to stop/disable the service and run chef-solo again.

[2015-08-20T22:32:12-06:00] WARN: Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in Chef 12 and will be removed. Use Chef::ProviderResolver.new(node, resource, action) instead.

This warning is new to chef-client 12.4.1. You will not have it in older versions of chef-client. arcgis cookbook uses 'windows' cookbook  to install required windows features. And 'windows' cookbook (by Chef software) uses a deprecated way of instantiating providers. We hope Chef Software will fix the problem soon.

Regards,
Pavel

**Comment by pkdavidson** [comment]
I should never post late at night... Just noticed what I posted...
I'll reset those accounts on our end.  Good thing this was just on an dev box under VM workstation.

Good to know about chef-client.  I'll pull that off the unit.
And I'll give the domain user account a test on another box in the next week.
