### ISSUE TITLE
ArcGIS Pro 2.3 on Win 10

### ISSUE THREAD

**Issue by azinsharaf** [Esri/arcgis-cookbook#207]
I am getting the following error when installing arcgis pro 2.3 from the cookbook 3.3.0 on a Window 10 machine. 

```
Microsoft Windows [Version 10.0.16299.1029]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>chef-solo -j C:\chef\roles\arcgis-pro.json
[2019-03-27T14:40:40-07:00] WARN: *****************************************
[2019-03-27T14:40:40-07:00] WARN: Did not find config file: C:/chef/client.rb, using command line options.
[2019-03-27T14:40:40-07:00] WARN: *****************************************
Starting Chef Client, version 13.9.4
resolving cookbooks for run list: ["ms_dotnet::ms_dotnet4", "arcgis-pro"]
Synchronizing Cookbooks:
  - ms_dotnet (3.2.1)
  - arcgis-pro (3.3.0)
  - windows (4.1.4)
  - arcgis-repository (3.3.0)
  - aws (7.3.1)
Installing Cookbook Gems:

Running handlers:
[2019-03-27T14:40:51-07:00] ERROR: Running exception handlers
Running handlers complete
[2019-03-27T14:40:51-07:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 10 seconds
[2019-03-27T14:40:51-07:00] FATAL: Stacktrace dumped to c:/chef/local-mode-cache/cache/chef-stacktrace.out
[2019-03-27T14:40:51-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-03-27T14:40:51-07:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of bundle install ----
STDOUT:
STDERR: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1097:in `<module:RbReadline>': HOME environment variable (or HOMEDRIVE and HOMEPATH) must be set and point to a directory (RuntimeError)
        from C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:17:in `<top (required)>'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/readline.rb:10:in `<module:Readline>'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/readline.rb:8:in `<top (required)>'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/line_editor/readline.rb:2:in `<top (required)>'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/line_editor.rb:2:in `<top (required)>'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:8:in `<top (required)>'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:2:in `<top (required)>'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendored_thor.rb:7:in `<top (required)>'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:4:in `<top (required)>'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:21:in `<top (required)>'
        from C:/opscode/chef/embedded/bin/bundle:23:in `load'
        from C:/opscode/chef/embedded/bin/bundle:23:in `<main>'
---- End output of bundle install ----
Ran bundle install returned 1

C:\WINDOWS\system32>
```

**Comment by azinsharaf** [comment]
Update:
The error was resolved by doing these 2 steps:
1- Instead of login with admin account (which does not have internet access in our org), login with regular account and run the command prompt as admin.
2- More importantly, Win 10 comes with  dotnet_451 so I removed `"recipe[ms_dotnet::ms_dotnet4]"` form the `run_list`.

**Comment by azinsharaf** [comment]
next issue: 
I get this weird message now. (attached.)
I just have ArcMap 10.4.1 on this machine not Pro. 
![pro_chef](https://user-images.githubusercontent.com/10101468/55121226-bad06400-50b6-11e9-8f52-6b75fd5e1d33.JPG)

**Comment by azinsharaf** [comment]
After doing lots of trial and error, I would be closing this issue and open a new Issue to discuss.
