### ISSUE TITLE
LoadError: cannot load such file -- java-properties/version

### ISSUE THREAD

**Issue by jesa-esrich** [Esri/arcgis-cookbook#261]
Currently testing the new Chef Cookbook 3.6.1 to install ArcGIS Server 10.8.1 and already receive an error when installing the Gems and compiling the Cookbooks: 

_Recipe Compile Error in c:/chef/local-mode-cache/cache/cookbooks/java_properties/libraries/java_properties_resource.rb
LoadError
cannot load such file -- java-properties/version_

**Environment:**
- Windows Server 2019 Datacenter
- The system has internet connectivity
- But the multipart-post-2.1.1 gem has already been installed on the machine

**System Info:**
- chef_version=14.14.29
- platform=windows
- platform_version=10.0.17763
- ruby=ruby 2.5.7p206 (2019-10-01 revision 67816) [x64-mingw32]
- program_name=C:/opscode/chef/bin/chef-solo
- executable=C:/opscode/chef/bin/chef-solo

I have checked the mentioned file and it is available in the folder and it's not blocked. Does anyone know what could cause this error? I have never received such error when working with the ArcGIS Cookbooks.

The chef-stacktrace.out is posted in the comments.

**Comment by jesa-esrich** [comment]
**chef-stacktrace.out**

_LoadError: cannot load such file -- java-properties/version
C:/opscode/chef/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/opscode/chef/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
c:/Chef/local-mode-cache/cache/cookbooks/java_properties/files/default/vendor/gems/java-properties-0.0.2/lib/java-properties.rb:2:in `<top (required)>'
C:/opscode/chef/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/opscode/chef/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
c:/chef/local-mode-cache/cache/cookbooks/java_properties/libraries/java_properties_resource.rb:5:in `<top (required)>'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:229:in `load'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:229:in `block in load_libraries_from_cookbook'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:224:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:224:in `load_libraries_from_cookbook'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:103:in `block in compile_libraries'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:102:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:102:in `compile_libraries'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:74:in `compile'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/run_context.rb:201:in `load'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/client.rb:515:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/client.rb:281:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/application.rb:279:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/application.rb:261:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/application/client.rb:449:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/application.rb:66:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/lib/chef/application/solo.rb:229:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29-universal-mingw32/bin/chef-solo:24:in `<top (required)>'
C:/opscode/chef/bin/chef-solo:81:in `load'
C:/opscode/chef/bin/chef-solo:81:in `<main>'_

**Comment by jesa-esrich** [comment]
Installing the gem java-properties-0.0.2 helped resolve the problem: https://rubygems.org/gems/java-properties/versions/0.0.2
However I never had to this before. Normally the gems would have been fetched from the web if they were missing...
