### ISSUE TITLE
The process monitor did not find the connection to the configuration store. The site may not have been initialized. After the site is initialized, the check for database processes will be reattempted.

### ISSUE THREAD

**Issue by sgavathe** [Esri/arcgis-cookbook#368]
@cameronkroeker
I get the below error under portal logs. I am using Chef cookbook for ArcGIS 11.0.

`
<type="VERBOSE" code="217063" source="Portal" process="27884" thread="1" methodName="" machine="FQDN" user="" elapsed="" requestID="">The process monitor did not find the connection to the configuration store. The site may not have been initialized. After the site is initialized, the check for database processes will be reattempted.</Msg>
`

for some strange reason, I can't get to http://localhost:7080/arcgis or https://localhost:7443/arcgis using curl 

both ports are listening already

portal service is up
`
systemctl status arcgisportal
● arcgisportal.service - Portal for ArcGIS Service 
Started Portal for ArcGIS Service.
`

I also see below under service log file

`
Exception in thread "main"
 java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy0.stop(Unknown Source)
        at com.esri.arcgis.portal.impl.Main.stop(Main.java:168)
        at com.esri.arcgis.portal.impl.Main.main(Main.java:457)
 Caused by: java.rmi.UnmarshalException: Error unmarshaling return header; nested exception is:
        java.io.EOFException
        at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(Unknown Source)
        at java.rmi/sun.rmi.server.UnicastRef.invoke(Unknown Source)
        at jdk.remoteref/jdk.jmx.remote.internal.rmi.PRef.invoke(Unknown Source)
        at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl_Stub.invoke(Unknown Source)
        at java.management.rmi/javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.invoke(Unknown Source)
        at java.management/javax.management.MBeanServerInvocationHandler.invoke(Unknown Source)
        ... 3 more
 Caused by: java.io.EOFException
        at java.base/java.io.DataInputStream.readByte(Unknown Source)
        ... 9 more
 Exception in thread "main"
 java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy0.stop(Unknown Source)
        at com.esri.arcgis.portal.impl.Main.stop(Main.java:168)
        at com.esri.arcgis.portal.impl.Main.main(Main.java:457)
 Caused by: java.rmi.UnmarshalException: Error unmarshaling return header; nested exception is:
        java.io.EOFException
        at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(Unknown Source)
        at java.rmi/sun.rmi.server.UnicastRef.invoke(Unknown Source)
        at jdk.remoteref/jdk.jmx.remote.internal.rmi.PRef.invoke(Unknown Source)
        at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl_Stub.invoke(Unknown Source)
        at java.management.rmi/javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.invoke(Unknown Source)
        at java.management/javax.management.MBeanServerInvocationHandler.invoke(Unknown Source)
        ... 3 more
 Caused by: java.io.EOFException
        at java.base/java.io.DataInputStream.readByte(Unknown Source)
 UTC 2023        ... 9 more
 `

**Comment by cameronkroeker** [comment]
Hi @sgavathe,

This error is expected to show up until a portal site is created, so it can be ignored:

```
<type="VERBOSE" code="217063" source="Portal" process="27884" thread="1" methodName="" machine="FQDN" user="" elapsed="" requestID="">The process monitor did not find the connection to the configuration store. The site may not have been initialized. After the site is initialized, the check for database processes will be reattempted.</Msg>
```

I am not quite sure what the second error is. Was there an issue with creating the portal site or what error shows up in the Chef run?

Do these commands return anything?

```bash
curl https://<ip>:7443/arcgis/portaladmin/healthCheck?f=json --insecure -v
```

or

```bash
curl https://<ip>:7443/arcgis/portaladmin?f=json --insecure -v
```

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
Thanks @sgavathe. Based on this error sounds like the internal tomcat server that portal uses is not starting properly:

```
Error checking status of web server. java.util.concurrent.TimeoutException
```

Let's check to see if there are any errors in: `<install dir>/arcgis/portal/framework/runtime/tomcat/logs`

One more thing to check is the server.xml file is not corrupted inside:

```
<install dir>/arcgis/portal/framework/runtime/tomcat/conf
```

**Comment by cameronkroeker** [comment]
Hi @sgavathe,

Honestly I am not quite sure what the issue could be. Can you share the chef run log and json config file? Scrub out any sensitive information such as passwords.

Have you tried uninstalling and running it again?

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
Thanks @sgavathe, one thing I notice off the bat is the json configuration file only contains the installation recipes in the run-list so this will only install. It doesnt authorize, create portal site or server site, doesn't register web adaptors or data store, and doesn't federate. The `recipe[arcgis-enterprise::enable_knowledgeserver]` will only work if all the above has been completed.

**Comment by cameronkroeker** [comment]
Thanks @sgavathe. Which Linux OS distribution is this running on?
