### ISSUE TITLE
Error: Unable to download data from https://rubygems.org/ 

### ISSUE THREAD

**Issue by bull-matt** [Esri/arcgis-cookbook#53]
Windows Server 2012 R2
ArcGIS 10.4.1
Chef 12.12.15

When trying to execute the 'arcgis-server::system' recipe I am receiving an an error:

_"Unable to download data from https://rubygems.org/ - Errno::ECONNABORTED: An established connection was aborted by the software in your host machine. - SSL_connect (https://api.rubygems.org/specs.4.8.gz)"._

Do you know how I can resolve this error?  More detailed output below.

Thanks
Matt

[2016-08-10T15:52:08+01:00] INFO: *** Chef 12.12.15 ***
[2016-08-10T15:52:08+01:00] INFO: Platform: x64-mingw32
[2016-08-10T15:52:08+01:00] INFO: Chef-client pid: 2464
[2016-08-10T15:52:16+01:00] INFO: Setting the run_list to ["recipe[arcgis-server::system]"] from CLI options
[2016-08-10T15:52:16+01:00] INFO: Run List is [recipe[arcgis-server::system]]
[2016-08-10T15:52:16+01:00] INFO: Run List expands to [arcgis-server::system]
[2016-08-10T15:52:16+01:00] INFO: Starting Chef Run for myserver.mydomain
[2016-08-10T15:52:16+01:00] INFO: Running start handlers
[2016-08-10T15:52:16+01:00] INFO: Start handlers complete.
[2016-08-10T15:52:16+01:00] INFO: HTTP Request Returned 404 Not Found: Object not found: 
[2016-08-10T15:52:24+01:00] INFO: Loading cookbooks [arcgis-server@2.3.0, hostsfile@2.4.5, limits@1.0.0, authbind@0.1.10, iptables@1.0.1, windows@1.39.2, openssl@4.0.0, ms_dotnet@2.4.0, chef_handler@1.1.7, chef-sugar@2.5.0]
[2016-08-10T15:52:25+01:00] WARN: "method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"]) at c:/chef/local-mode-cache/cache/cookbooks/chef_handler/attributes/default.rb:23:in `from_file' at C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
[2016-08-10T15:52:25+01:00] INFO: Processing chef_gem[multipart-post] action install (arcgis-server::system line 20)
[2016-08-10T15:52:27+01:00] WARN:  failed to find gem multipart-post (>= 0) from [https://rubygems.org/]
[2016-08-10T15:52:30+01:00] ERROR: chef_gem[multipart-post] (arcgis-server::system line 20) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of C:/opscode/chef/embedded/bin/gem install "multipart-post" -q --no-rdoc --no-ri  ----
STDOUT: 
STDERR: ERROR:  Could not find a valid gem 'multipart-post' (>= 0), here is why:

          Unable to download data from https://rubygems.org/ - Errno::ECONNABORTED: An established connection was aborted by the software in your host machine. - SSL_connect (https://api.rubygems.org/specs.4.8.gz)

**Comment by pbobov** [comment]
It looks like Chef was not able to install multipart-post gem because connection to  https://api.rubygems.org/specs.4.8.gz was blocked by a firewall.

Before running chef, please try to install the gem manually.
```
>gem install multipart-post
```

**Comment by bull-matt** [comment]
Thanks for responding so quickly.  The local install seems to have worked.
